baseURL = "https://kian-alasvandi.github.io/kian-blog/"
title = "Kian Security"
theme = "PaperMod"
defaultContentLanguage = "en"
pagination.pagerSize = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "Kian"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = false

[params.homeInfoParams]
  Title = "Kian Security Blog"
  Content = """
Linux • Windows • Networking • Bug Bounty • Reverse Engineering
"""

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 50

[[menu.main]]
identifier = "writeups"
name = "Writeups"
url = "/writeups/"
weight = 60

[taxonomies]
category = "categories"
tag = "tags"